name: "Export Godot"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: 
      - release
      - staging
      - Mobile

env:
  GODOT_VERSION: 3.4.4
  git_branch: ${{ github.ref_name }}

jobs:

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: ./run prepare:ci
      #- if: ${{ github.ref == 'refs/heads/release' }}
      - run: ./run export:web
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          clean: false
